routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

\App::setLocale('es');

Route::get('/', function () 
{
    return redirect()->route('login');
});

Route::post('conekta/webhook', function() {
    $body = @file_get_contents('php://input');
    $data = json_decode($body);
    http_response_code(200); // Return 200 OK
    //if ($data->type == 'charge.paid'){
    if ($data->type){
      $payment_method = $data->payment_method->type;
      $msg = "Tu pago ha sido comprobado.";
      mail("client@email.com","Pago ". $payment_method ." confirmado",$msg);
    }
});

Route::get('/reglas',
        function () {
            return view('reglas');
})->name('reglas');

Route::get('/instructivo',function()
{
    return view('participantes/instructivo');
})->name('instructivo');

Route::get('/participantes/reglas', [
	    'uses'=>'ParticipantesController@juegoReglas',
	    'as'=>'participantes.juegoReglas',
]);

   // Authentication Routes...
    $router->get('login', 'Auth\LoginController@showLoginForm')->name('login');
    $router->post('login', 'Auth\LoginController@login');
    $router->post('logout', 'Auth\LoginController@logout')->name('logout');

    // Registration Routes...
    $router->get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
    $router->post('register', 'Auth\RegisterController@register');

    // Password Reset Routes...
    $router->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    $router->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    $router->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    $router->post('password/reset', 'Auth\ResetPasswordController@reset');


Route::group(['middleware' => ['auth']], function() {
    
    /*    
    Route::get('/torneo-500', [
        'as'=>'torneo500',
        'uses' => 'HomeController@torneo500',
    ]);
    */
    
    //Agrega la relación a el torneo cuando se compra una entrada
    
    /*Ruta de paypal liga mx
    Route::get('/jvhzsdyiglGFHA8-w1231-8-torneo-apertura-2019', [
        'uses' => 'ParticipantesController@torneoClausuraPaypal',
        'as'=>'particioantes.torneoClausuraPaypal',
    ]);
    //Ruta de transferencia liga mx*/
    Route::post('/torneo-liga-mx', [
        'uses' => 'ParticipantesController@torneoClausuraTransferencia',
        'as'=>'particioantes.torneoClausuraTransferencia',
    ]);
    
    
    //Ruta de paypal liga mx revancha
    Route::get('/sdasfgfbdsdfFDGGR&W8-w12432fd-torneo-apertura-2019', [
        'uses' => 'ParticipantesController@torneoRevanchaPaypal',
        'as'=>'particioantes.torneoClausuraRevanchaPaypal',
    ]);
    //Ruta de transferencia liga mx revancha
    Route::post('/torneo--revancha-liga-mx-2019', [
        'uses' => 'ParticipantesController@torneoRevanchaTransferencia',
        'as'=>'particioantes.torneoRevanchaTransferencia',
    ]);
    
    
    
    Route::post('/storagefile','formController@storage');
    
    Route::put('/archvio/update/{id}',[
        'uses' => 'formController@update',
        'as'=>'archivos.update',
    ]);
    
    Route::get('/form/index',[
        'uses' => 'formController@index',
        'as'=>'archivos.index',
    ]);
    
    Route::get('/createfile','formController@create');
    
    
    Route::get('/home', [
        'as'=>'home',
        'uses' => 'HomeController@index',
    ]);
    
    Route::get('/participantes', [
        'as'=>'participantes',
        'uses' => 'HomeController@participantes',
    ]);
    
    
    
    //Juegos
        Route::get('/juegos2', [
        	    'as'=>'juegos.index2',
        	    'uses'=>'JuegosController@index2'
        ]);
        
        Route::resource('/juegos','JuegosController');
        
        
        Route::get('/participantes/perfil-usuario', [
                'uses' => 'ParticipantesController@userPerfil',
                'as'   => 'participantes.userPerfil'
        ]);     
        Route::get('/participantes/perfil-usuario/update', [
                'uses' => 'ParticipantesController@updatePass',
                'as'   => 'participantes.updatePass'
        ]);
        Route::get('/participantes/jugadores', [
                'uses' => 'ParticipantesController@juegoParticipantes',
                'as'   => 'participantes.juegoParticipantes'
        ]);
        
        //Seleccion y apuesta de equipos
        Route::post('/juegos/apostar', [
                'uses' => 'JuegosController@createEquipos',
                'as'   => 'juegos.createEquipos'
        ]);
        Route::get('/juegos/{id}/apostar/storeEquipo', [
                'uses' => 'JuegosController@storeEquipo',
                'as'   => 'juegos.storeEquipo'
        ]);
        
        /*
        Route::get('/participantes/comprar-entrada', [
                'uses' => 'ParticipantesController@comprarEntrada',
                'as'   => 'participantes.comprarEntrada'
        ]);

          
        Route::get('/participantes/comprar-entrada-revancha', [
                'uses' => 'ParticipantesController@comprarEntradaRevancha',
                'as'   => 'participantes.comprarEntradaRevancha'
        ]);
        */
        
    Route::group( ['middleware' => ['role:admin'] ], function() {
        
        //Administración
        Route::get('/administracion', [
                'uses' => 'AdministracionController@index',
                'as'   => 'administracion.index'
        ]);
        
        Route::post('/administracion/enviar', [
                'uses' => 'AdministracionController@sendMail',
                'as'   => 'administracion.sendMail'
        ]);
        
        Route::post('/administracion/enviarRecordatorio', [
                'uses' => 'AdministracionController@sendMailRecordatorio',
                'as'   => 'administracion.sendMailRecordatorio'
        ]);
        
        
        //Torneo
        Route::get('/torneo/storeTorneo', [
                'uses' => 'TorneoController@storeTorneo',
                'as'   => 'torneo.storeTorneo'
        ]);
        Route::get('/torneo/crearTorneo', [
                'uses' => 'TorneoController@crearTorneo',
                'as'   => 'torneo.crearTorneo'
        ]);
        Route::get('/torneo/principal', [
                'uses' => 'TorneoController@principal',
                'as'   => 'torneo.principal'
        ]);
        //jornadas
        Route::get('/torneo/{id}/jornadas/', [
                'uses' => 'TorneoController@torneoJornadas',
                'as'   => 'torneo.jornadas'
        ]);
        Route::get('/torneo/{id}/jornadas/create-jornada', [
                'uses' => 'TorneoController@createJornada',
                'as'   => 'torneo.createJornada'
        ]);
        Route::get('/torneo/{id}/jornadas/store-jornada', [
                'uses' => 'TorneoController@storeJornada',
                'as'   => 'torneo.storeJornada'
        ]);
        Route::get('/torneo/{id}/jornadas/delete-jornada', [
                'uses' => 'TorneoController@destroyJornada',
                'as'   => 'torneo.destroyJornada'
        ]);
        Route::get('/torneo/{id}/jornadas/update-jornada', [
                'uses' => 'TorneoController@updateJornada',
                'as'   => 'torneo.updateJornada'
        ]);
        //Partidos de jornada
        Route::get('/torneo/jornadas/{id}/edit-jornada', [
                'uses' => 'JuegosController@editJornada',
                'as'   => 'partidos.editJornada'
        ]);
        Route::get('/torneo/jornadas/partidos/{id}', [
                'uses' => 'JuegosController@jornadaPartidos',
                'as'   => 'partidos.jornadaPartidos'
        ]);
        Route::get('/torneo/jornadas/{id}/crear-partidos', [
                'uses' => 'JuegosController@createPartidos',
                'as'   => 'partidos.createPartidos'
        ]);
        Route::get('/torneo/jornadas/{id}/editPartido', [
                'uses' => 'JuegosController@editPartido',
                'as'   => 'partidos.editPartido'
        ]);
        Route::get('/torneo/jornadas/{id}/updateEquipo', [
                'uses' => 'JuegosController@updateEquipo',
                'as'   => 'partidos.updateEquipo'
        ]);
        Route::get('/torneo/jornadas/partidos/{id}/store-partidos', [
                'uses' => 'JuegosController@storePartido',
                'as'   => 'partidos.storePartido'
        ]);
        Route::get('/torneo/jornadas/partidos/{id}/delete-partidos/', [
                'uses' => 'JuegosController@eliminarPartido',
                'as'   => 'partidos.eliminarPartido'
        ]);
        //rutas de equipos
        Route::resource('/equipos','EquipoController');
        
        Route::get('/equipos/create/storeEquipo/', [
                'uses' => 'EquipoController@storeEquipo',
                'as'   => 'equipos.storeEquipo'
        ]);
        Route::get('/equipos/create/destroyEquipo/{id}', [
                'uses' => 'EquipoController@destroyEquipo',
                'as'   => 'equipos.destroyEquipo'
        ]);
        Route::get('/equipos/{id}/edit/updateEquipo', [
                'uses' => 'EquipoController@updateEquipo',
                'as'   => 'equipos.updateEquipo'
        ]);
        //enviar mails de vidas
        Route::get('/email-vidas/{id}', [
                'uses' => 'MailController@mailVidas',
                'as'   => 'emails.mailVidas'
        ]);
        
        Route::get('email', function() {
                return new \App\Mail\RecordatorioUser();
        });
        
        Route::get('emailvidas', function() {

app/Regla.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Regla extends Model
{
    //
}

app/Http/Controllers/ReglasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Regla;

class ReglasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $regla = Regla::find($id);
        return view('reglas.show', ['regla' => $regla]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/reglas/create.blade.php
@extends('layouts.admin')
@section('pageTitle', 'Crear Equipo')
@section('content')

    <div id="page-content-wrapper">
        <div class="container-fluid">
            <div class="jumbotron">
                <div class="row">
    <div class="col-md-12">
        <div class="panel panel-personalizado">
          <div class="panel-heading">
            <h3 class="panel-title panel-title-color">Nuevo Equipo</h3>
          </div>
          <div class="panel-body">
              <div class="row">
                    <div class="col-sm-4 col-sm-push-10">
                        <input type="button" class="btn btn-danger " onclick="history.back()" name="volver atrás" value="Regresar">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">

                    {!! Form::open(array('route' => 'equipos.store','method'=>'POST','files'=> true)) !!}
                                <div class="row">
                                     <div class="col-md-12">
                                     <div class="form-group">
                                        {{Form::label('equipo', 'Nombre del Equipo', array('class' => 'awesome'))}}
                                        {{ Form::text('equipo',null,['class' => 'form-control validate'])}}
                                    </div>
                                    </div>
                                 </div>
                               <div class="form-group m-b-0">
                                            {{Form::label('escudo', 'Seleccionar Escudo', array('class' => 'control-label awesome'))}}
                                            {{ Form::file('escudo',null,['class' => 'filestyle validate','data-buttonname'=>'btn-primary'])}}
                                            
                                </div>
                                <div class="form-group m-b-0">
                                    <div class="col-sm-2 col-sm-push-10">
                                        <br>
                                        {{ Form::submit('Registrar',array('class'=>'btn btn-primary waves-effect waves-light'))}}
                                    </div>
                                </div>
                    {{ Form::close() }}
                    </div>
                </div>
          </div>
        </div>
    </div>
</div>
                
            </div>
        </div>
    </div>
@endsection

resources/views/reglas/edit.blade.php
@extends('layouts.admin')
@section('pageTitle', 'Editar Equipo')
@section('content')

    <div id="page-content-wrapper">
        <div class="container-fluid">
            <div class="jumbotron">
                <div class="row">
    <div class="col-md-12">
        <div class="panel panel-personalizado">
          <div class="panel-heading">
            <h3 class="panel-title panel-title-color">Editar Equipo</h3>
          </div>
          <div class="panel-body">
              <div class="row">
                    <div class="col-sm-4 col-sm-push-10">
                        <input type="button" class="btn btn-danger " onclick="history.back()" name="volver atrás" value="Regresar">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                    {{ Form::model($equipo, array('route' => array('equipos.update', $equipo->id), 'method' => 'PUT', 'files'=> true)) }}
                                <div class="row">
                                     <div class="col-md-12">
                                     <div class="form-group">
                                        {{Form::label('equipo', 'Nombre del Equipo', array('class' => 'awesome'))}}
                                        {{ Form::text('equipo',null,['class' => 'form-control validate'])}}
                                    </div>
                                    </div>
                                 </div>
                               <div class="form-group m-b-0">
                                            {{Form::label('escudo', 'Seleccionar Escudo', array('class' => 'control-label awesome'))}}
                                            {{ Form::file('escudo',null,['class' => 'filestyle validate','data-buttonname'=>'btn-primary'])}}
                                            
                                </div>
                                <div class="form-group m-b-0">
                                    <div class="col-sm-2 col-sm-push-10">
                                        <br>
                                        {{ Form::submit('Actualizar',array('class'=>'btn btn-primary waves-effect waves-light'))}}
                                    </div>
                                </div>
                    {{ Form::close() }}
                    </div>
                </div>
          </div>
        </div>
    </div>
</div>
                
            </div>
        </div>
    </div>
@endsection

resources/views/reglas/index.blade.php
@extends('layouts.admin')
@section('pageTitle', 'Equipos')
@section('content')

        
            <div id="page-content-wrapper">
        <div class="container-fluid">
            <div class="jumbotron">
                <div class="row">
                    <div class="col-md-12">
                        <div class="panel panel-personalizado">
                          <div class="panel-heading">
                           
                            <h3 class="panel-title panel-title-color">Partidos</h3>
                          </div>
                          <div class="panel-body">
                               <div class="row">
                                    <div class="col-sm-4 col-sm-push-8">
                                        <a class="btn btn-primary" href="{{route('equipos.create')}}">Nuevo Equipo</a>
                                        
                                            <input type="button" class="btn btn-danger " onclick="history.back()" name="volver atrás" value="Regresar">
                                     
                                    </div>
                                </div>
                                <br />
                                <div class="row">
                                    <div class="col-md-12">
                                        @if(count($equipos)>0)
                                        <table class="table table-text2 table-striped table-bordered">
                                            <thead>
                                                <th>Equipo</th>
                                                <th>Escudo</th>
                                                <th>Acción</th>
                                            </thead>
                                            <tbody>
                                                @foreach($equipos as $equipo)
                                                <tr>
                                                    <td>{{$equipo->equipo}}</td>
                                                    <td><img src="{{ asset('images/equipos/'.$equipo->escudo) }}" style=" width: 17%;"></img></td>
                                                    <td>
                                                        <a href="{{route('equipos.destroyEquipo',[$equipo->id])}}" class="btn btn-danger">Eliminar</a>
                                                        <a href="{{route('equipos.edit',[$equipo->id])}}" class="btn btn-primary">Editar</a>
                                                    </td>
                                                    
                                                </tr>
                                                @endforeach
                                            </tbody>
                                            
                                        </table>
                                        @else
                                        <h3>No hay equipos registros</h3>
                                        @endif
                                    </div>
                                </div>
                          </div>
                        </div>
                    </div>
                </div>
                
                <br />
                
            </div>
        </div>
    </div>
@endsection

resources/views/reglas/show.blade.php
@extends('layouts.registro')
@section('pageTitle', 'Principal')
    @section('content')
        <section>
            <div class="container">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="wrapper-page">
                            <div class="m-t-80 card-box">
                                
                                <div class="col-sm-12 text-right">
                                    <a href="javascript:history.back(1)">
                                        Regresar
                                    </a>
                                </div>
                                
                            <div class="text-center">
                                <h2 class="text-uppercase m-t-0 m-b-30">
                                    <a href="index.html" class="text-success">
                                        <span><img src="{{ asset('images/logo.png') }}" alt="" height="120"></span>
                                        
                                    </a>
                                </h2>
                                <h4 class="text-uppercase font-bold m-b-0">{{' ' . $regla->nombre  }} <img src="@if($regla->nombre =='Reglas NFL') {{asset('images/log_nfl.jpg')}} @else {{asset('images/ligamx.png')}}   @endif" width="50"></img></h4>
                            </div>
                            
                            <div class="col-sm-12">
                                <br>
                                <br>
                            </div>
                            
                            <div class="panel-body">
                                
                                <div class="account-content">
                                    <?php echo $regla->contenido; ?>
                                </div>
                            
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection